// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// VerificationMailer is an autogenerated mock type for the VerificationMailer type
type VerificationMailer struct {
	mock.Mock
}

// SendEmailVerification provides a mock function with given fields: name, email, link
func (_m *VerificationMailer) SendEmailVerification(name string, email string, link string) error {
	ret := _m.Called(name, email, link)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(name, email, link)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
